### PR TITLE
Fixed #69

### LINKED ISSUE #69: on master branch, extension no longer shows 'fund issue' button on github issue
on master branch (the version thats in the chrome store), extension no longer shows 'fund issue' button on github issue .

i'm using Chrome Version 73.0.3683.103 (Official Build) (64-bit).

the expected behaviour looks like this:

1_cm0UEfYsQo0t9LOjD2XZzw

scope of this is to fix this issue on the master branch

### PR DESCRIPTION
**Pull request by gutsal-arsen**
CORS handler is still needed on server-side

### CODE REVIEW

**Comment by owocki** [comment]
testing this now. 

notes:
1. is there a PR in for the CORS header change for the server?
2. other than that, it seems to work fine.  thanks!

**Comment by gutsal-arsen** [comment]
@owocki  from what  I see there's no PR. Can't make it as I'm not Python developer.

**Comment by owocki** [comment]
got it; what needs to be jchanged for the gitcoin.co address? just allowing cross-origin requetss from github.com?

**Comment by owocki** [comment]
fund issue button doesnt work.  screencast => http://bits.owocki.com/f29beeb4548d/Screen%20Recording%202019-04-26%20at%2010.45%20AM.gif

**Comment by gutsal-arsen** [comment]
@owocki gimme browser and version

**Comment by gutsal-arsen** [comment]
@owocki added small fix (`event.stopPropagation()`) that might cause that strange behavior. Please check

**Comment by owocki** [comment]
chrome Version 73.0.3683.103 (Official Build) (64-bit)

**Comment by gutsal-arsen** [comment]
@owocki recent update (yesterday one) contains the fix (explained one message above).

**Comment by gutsal-arsen** [comment]
@owocki tested recent update?

**Comment by owocki** [comment]
still not working http://bits.owocki.com/782153851b0b/Screen%20Recording%202019-04-29%20at%2003.01%20PM.gif

latest commit of the version im testing is 4824268e200fd1368eb8798575a4f5194bae78d9

**Comment by owocki** [comment]
oh wait i needed to `yarn build`!

**Comment by owocki** [comment]
mind submitting your work on the gitcoin bounty?

**Comment by gutsal-arsen** [comment]
@owocki it's already been submitted. Payment reminder just sent.

**Pull request merged**
