### PR TITLE
Fix grammatical issue

### PR DESCRIPTION
**Pull request by arun1595**
What it Do -> What it does

P.S. This is really a minor thing but it was bugging me so I decided to submit a PR :smile:

### CODE REVIEW

**Comment by gasolin** [comment]
@arun1595 I'v rewrtten ths part with fecth in the https://github.com/gitcoinco/browser-extension/pull/48, so no need to fix this comment anymore

**Comment by arun1595** [comment]
@gasolin I guess you meant to leave the comment on https://github.com/gitcoinco/browser-extension/pull/53

**Comment by mbeacom** [comment]
@arun1595 I'd be up for changing this copy to: `What it does` or completely removing that header block.

**Comment by arun1595** [comment]
@mbeacom Updated it to 'What it does'.

**Comment by mbeacom** [comment]
@arun1595 Thanks!

**Pull request merged**
